;;; key setting
(define-prefix-command 'ctl-cc-map)
(define-prefix-command 'ctl-co-map)     ; org-mode-map-prefix
(define-prefix-command 'ctl-z-map)

;; global key binding
(deh-section "global-kbd"
  (deh-define-key global-map
    ((kbd "C-z")   . 'ctl-z-map)
    ((kbd "C-d")   . 'delete-char-or-region)
    ((kbd "C-1")   . 'smart-mark-whole-sexp)
    ((kbd "C-2")   . 'set-mark-command)
    ((kbd "C-m")   . 'newline-and-indent)
    ((kbd "C-j")   . 'newline)
    ((kbd "C-a")   . 'my-beginning-of-line)
    ((kbd "C-e")   . 'my-end-of-line)
    ((kbd "C-o")   . 'vi-open-next-line)
    ((kbd "C-'")   . 'redo)
    ((kbd "C-\\")  . 'my-comment-or-uncomment-region)
    ((kbd "M-5")   . (lambda () (interactive) (message (buffer-file-name (current-buffer)))))
    ((kbd "M-0")   . 'other-window)
    ((kbd "M-1")   . 'sdcv-search)
    ((kbd "M-9")   . 'sr-speedbar-select-window)
    ((kbd "M-'")   . 'just-one-space)
    ((kbd "M-f")   . 'ywb-camelcase-forward-word)
    ((kbd "M-b")   . 'ywb-camelcase-backward-word)
    ((kbd "M-m")   . 'smart-mark)
    ;; ((kbd "C-`")   . 'ywb-toggle-case-dwim)
    ;; ((kbd "C-SPC") . 'toggle-input-method)
    ;; ((kbd "M-g g") . 'ywb-goto-line)
    ;; ((kbd "<f5>")  . 'browse-el-find-funtion)
    ;; ((kbd "<f6>")  . 'browse-el-go-back)
    ((kbd "<f5> <f5>") . (lambda () (interactive) (revert-buffer nil t nil)))
    ((kbd "<f6>")  . (lambda () (interactive) (sr-speedbar-toggle) (sr-speedbar-select-window)))
    ((kbd "<f11>") . 'w3m)
    ((kbd "<f12>") . (lambda () (interactive) (switch-to-buffer (other-buffer))))
    ((kbd "<f8>")  . 'org-agenda)
    ((kbd "<f7>")  . 'calendar)
    ;; ((kbd "C-'")   . 'comment-dwim)
    ;; ((kbd "S-SPC") . 'set-mark-command)
    ;; ((kbd "M-#")   . 'ywb-shell-command-background)
    ;; ((kbd "M-2")   . 'ywb-mark-sexp)
    ;; ((kbd "M-3")   . 'ywb-sdcv-word)
    ((kbd "M-RET") . 'muse-insert-list-item)
    ((kbd "C-h j") . 'info-elisp)
    ((kbd "C-x C-k") . (lambda () (interactive) (kill-buffer (current-buffer))))
    ((kbd "C-x C-_") . 'fit-frame)
    ((kbd "<C-down-mouse-1>") . 'undefined)
    )

  (deh-define-key (lookup-key global-map "\C-c")
    ("$" . 'toggle-truncate-lines)
    ("a" . 'sourcepair-load)
    ("b" . 'bm-toggle)
    ("c" . 'ctl-cc-map)
    ;; ("d" . 'dirtree-show)
    ("f" . 'comint-dynamic-complete)
    ("g" . 'fold-dwim-hide-all)
    ;; ("h" . 'help-dwim)
    ("i" . 'imenu)
    ("j" . 'ffap)
    ("k" . 'auto-fill-mode)
    ("n" . 'bm-next)
    ("m" . 'switch-major-mode)
    ("p" . 'bm-previous)
    ("s" . 'ywb-create/switch-scratch)
    ("u" . 'revert-buffer)
    ("v" . 'imenu-tree)
    ("w" . 'ywb-favorite-window-config)
    ("\C-o" . 'browse-url-at-point)
    ;; ("\C-s" . (lambda() (interactive) (switch-to-buffer "*scratch*")))
    ("\C-t" . 'his-transpose-windows)
    )

  (deh-define-key (lookup-key global-map "\C-x")
    ("\C-t" . 'transpose-sexps)
    ("\C-r" . 'find-file-root)
    ("t"    . 'template-simple-expand-template)
    ("m"    . 'message-mail)
    ("c"    . 'ywb-clone-buffer)
    ("j"    . 'jump-to-register)
    ("an"   . 'tempo-forward-mark)
    ("ap"   . 'tempo-backward-mark)
    ("{"    . 'ywb-change-window-size)
    )

  (deh-define-key ctl-cc-map
    ("a" . 'org-agenda)
    ("b" . 'org-iswitchb)
    ("d" . 'deh-customize-inplace)
    ("f" . 'find-library)
    ("i" . 'ispell-word)
    ("l" . 'org-store-link)
    ("h" . 'highlight-regexp)
    ("n" . 'hi-lock-next)
    ("p" . 'hi-lock-previous)
    ("o" . 'ywb-org-table-convert-region)
    ("r" . 'compile-dwim-run)
    ("s" . 'compile-dwim-compile)
    ("t" . 'ywb-org-table-export-here)
    ("v" . 'view-mode)
    ("x" . 'incr-dwim)
    ("z" . 'decr-dwim)
    ("\t" . 'ispell-complete-word)
    )


  (deh-define-key ctl-z-map
    ("\C-z" . (if (eq window-system 'x) 'suspend-frame 'suspend-emacs))))

(windmove-default-keybindings)

(deh-define-key minibuffer-local-map
  ("\t" . 'comint-dynamic-complete))
(deh-define-key read-expression-map
  ("\t" . 'PC-lisp-complete-symbol))

(deh-section "dired-kdb"
  (add-hook 'dired-mode-hook
            (lambda ()
              (deh-define-key dired-mode-map
                ( "z"    . 'ywb-dired-compress-dir)
                ( "b"    . 'ywb-list-directory-recursive)
                ( "E"    . 'ywb-dired-w3m-visit)
                ( "j"    . 'ywb-dired-jump-to-file)
                ( "J"    . 'woman-dired-find-file)
                ( " "    . 'ywb-dired-count-dir-size)
                ( "r"    . 'wdired-change-to-wdired-mode)
                ( "W"    . 'ywb-dired-copy-fullname-as-kill)
                ( "a"    . 'ywb-add-description)
                ( "\C-q" . 'ywb-dired-quickview)
                ( "/r"   . 'ywb-dired-filter-regexp)
                ( "/."   . 'ywb-dired-filter-extension)
                ))))
