application: bookcabi
version: 1
runtime: python
api_version: 1

handlers:
- url: /notes-cpp
  static_dir: notes-cpp

- url: /akabook
  static_dir: akabook

- url: /perl-toc
  static_dir: perl-toc

- url: /.*
  script: books.py
